apiVersion: v1
kind: Pod
metadata:
  name: node-pod
  namespace: node-app

spec:
  containers:
    - name: node-container
      image: infrawave/node-app-cicd:01
      ports:
        - containerPort: 8000
